<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "users_venues_ratings_responses".
 *
 * @property integer $id
 * @property integer $user_venue_rating_id
 * @property integer $user_venue_rating_responding_user_id
 * @property string $user_venue_rating_response
 * @property string $user_venue_rating_response_date
 * @property integer $user_venue_rating_response_read
 * @property string $user_venue_rating_response_read_date
 *
 * @property \app\models\UsersVenuesRatings $userVenueRating
 * @property string $aliasModel
 */
abstract class UsersVenuesRatingsResponses extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users_venues_ratings_responses';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_venue_rating_id', 'user_venue_rating_responding_user_id', 'user_venue_rating_response_read'], 'integer'],
            [['user_venue_rating_response'], 'string'],
            [['user_venue_rating_response_date', 'user_venue_rating_response_read_date'], 'safe'],
            [['user_venue_rating_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\UsersVenuesRatings::className(), 'targetAttribute' => ['user_venue_rating_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_venue_rating_id' => 'User Venue Rating ID',
            'user_venue_rating_responding_user_id' => 'User Venue Rating Responding User ID',
            'user_venue_rating_response' => 'User Venue Rating Response',
            'user_venue_rating_response_date' => 'User Venue Rating Response Date',
            'user_venue_rating_response_read' => 'User Venue Rating Response Read',
            'user_venue_rating_response_read_date' => 'User Venue Rating Response Read Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserVenueRating()
    {
        return $this->hasOne(\app\models\UsersVenuesRatings::className(), ['id' => 'user_venue_rating_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\UsersVenuesRatingsResponsesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\UsersVenuesRatingsResponsesQuery(get_called_class());
    }


}
