<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "users_venues_ratings".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $venue_id
 * @property integer $venue_rating_cat_1
 * @property integer $venue_rating_cat_2
 * @property integer $venue_rating_cat_3
 * @property integer $venue_rating_cat_4
 * @property integer $venue_rating_cat_5
 * @property integer $venue_rating_cat_6
 * @property string $venue_rating_average
 * @property string $venue_rating_comment
 * @property string $venue_rating_date
 * @property integer $venue_rating_acknowledged
 * @property integer $venue_rating_resolved
 * @property string $venue_rating_date_resolved
 * @property string $venue_rating_resolve_expiration
 * @property integer $venues_updated
 *
 * @property \app\models\Users $user
 * @property \app\models\Venues $venue
 * @property \app\models\UsersVenuesRatingsImages[] $usersVenuesRatingsImages
 * @property \app\models\UsersVenuesRatingsResponses[] $usersVenuesRatingsResponses
 * @property string $aliasModel
 */
abstract class UsersVenuesRatings extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users_venues_ratings';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'venue_id', 'venue_rating_cat_1', 'venue_rating_cat_2', 'venue_rating_cat_3', 'venue_rating_cat_4', 'venue_rating_cat_5', 'venue_rating_cat_6', 'venue_rating_acknowledged', 'venue_rating_resolved', 'venues_updated'], 'integer'],
            [['venue_rating_average'], 'number'],
            [['venue_rating_comment'], 'string'],
            [['venue_rating_date', 'venue_rating_date_resolved', 'venue_rating_resolve_expiration'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Users::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['venue_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Venues::className(), 'targetAttribute' => ['venue_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'venue_id' => 'Venue ID',
            'venue_rating_cat_1' => 'Venue Rating Cat 1',
            'venue_rating_cat_2' => 'Venue Rating Cat 2',
            'venue_rating_cat_3' => 'Venue Rating Cat 3',
            'venue_rating_cat_4' => 'Venue Rating Cat 4',
            'venue_rating_cat_5' => 'Venue Rating Cat 5',
            'venue_rating_cat_6' => 'Venue Rating Cat 6',
            'venue_rating_average' => 'Venue Rating Average',
            'venue_rating_comment' => 'Venue Rating Comment',
            'venue_rating_date' => 'Venue Rating Date',
            'venue_rating_acknowledged' => 'Venue Rating Acknowledged',
            'venue_rating_resolved' => 'Venue Rating Resolved',
            'venue_rating_date_resolved' => 'Venue Rating Date Resolved',
            'venue_rating_resolve_expiration' => 'Venue Rating Resolve Expiration',
            'venues_updated' => 'Venues Updated',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'venue_rating_cat_1' => 'Default: Service',
            'venue_rating_cat_2' => 'Default: Staff',
            'venue_rating_cat_3' => 'Default: Facility',
            'venue_rating_cat_4' => 'Default: Custom 1',
            'venue_rating_cat_5' => 'Default: Custom 2',
            'venue_rating_cat_6' => 'Default: Custom 3',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\Users::className(), ['id' => 'user_id'])->inverseOf('usersVenuesRatings');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVenue()
    {
        return $this->hasOne(\app\models\Venues::className(), ['id' => 'venue_id'])->inverseOf('usersVenuesRatings');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsersVenuesRatingsImages()
    {
        return $this->hasMany(\app\models\UsersVenuesRatingsImages::className(), ['user_venue_rating_id' => 'id'])->inverseOf('userVenueRating');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsersVenuesRatingsResponses()
    {
        return $this->hasMany(\app\models\UsersVenuesRatingsResponses::className(), ['user_venue_rating_id' => 'id'])->inverseOf('userVenueRating');
    }


    
    /**
     * @inheritdoc
     * @return \app\models\UsersVenuesRatingsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\UsersVenuesRatingsQuery(get_called_class());
    }


}
