<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "users_venues_coupons".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $venue_coupon_id
 * @property string $user_venue_coupon_award_date
 * @property string $user_venue_coupon_exp
 * @property integer $user_venue_coupon_active
 * @property string $user_venue_coupon_title
 * @property string $user_venue_coupon_desc
 *
 * @property \app\models\Users $user
 * @property \app\models\VenuesCoupons $venueCoupon
 * @property string $aliasModel
 */
abstract class UsersVenuesCoupons extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users_venues_coupons';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'venue_coupon_id', 'user_venue_coupon_active'], 'integer'],
            [['user_venue_coupon_award_date', 'user_venue_coupon_exp'], 'safe'],
            [['user_venue_coupon_title'], 'string', 'max' => 100],
            [['user_venue_coupon_desc'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Users::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['venue_coupon_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\VenuesCoupons::className(), 'targetAttribute' => ['venue_coupon_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'venue_coupon_id' => 'Venue Coupon ID',
            'user_venue_coupon_award_date' => 'User Venue Coupon Award Date',
            'user_venue_coupon_exp' => 'User Venue Coupon Exp',
            'user_venue_coupon_active' => 'User Venue Coupon Active',
            'user_venue_coupon_title' => 'User Venue Coupon Title',
            'user_venue_coupon_desc' => 'User Venue Coupon Desc',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\Users::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVenueCoupon()
    {
        return $this->hasOne(\app\models\VenuesCoupons::className(), ['id' => 'venue_coupon_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\UsersVenuesCouponsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\UsersVenuesCouponsQuery(get_called_class());
    }


}
