<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "users_venues_ratings".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $venue_id
 * @property integer $venue_rating
 * @property string $venue_rating_comment
 * @property string $venue_rating_date
 * @property integer $venue_rating_acknowledged
 *
 * @property \app\models\Users $user
 * @property \app\models\Venues $venue
 * @property \app\models\UsersVenuesRatingsImages[] $usersVenuesRatingsImages
 * @property \app\models\UsersVenuesRatingsResponses[] $usersVenuesRatingsResponses
 * @property string $aliasModel
 */
abstract class UsersVenuesRatings extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users_venues_ratings';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'venue_id', 'venue_rating', 'venue_rating_acknowledged'], 'integer'],
            [['venue_rating_comment'], 'string'],
            [['venue_rating_date'], 'safe'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Users::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['venue_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Venues::className(), 'targetAttribute' => ['venue_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'venue_id' => 'Venue ID',
            'venue_rating' => 'Venue Rating',
            'venue_rating_comment' => 'Venue Rating Comment',
            'venue_rating_date' => 'Venue Rating Date',
            'venue_rating_acknowledged' => 'Venue Rating Acknowledged',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\Users::className(), ['id' => 'user_id'])->inverseOf('usersVenuesRatings');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVenue()
    {
        return $this->hasOne(\app\models\Venues::className(), ['id' => 'venue_id'])->inverseOf('usersVenuesRatings');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsersVenuesRatingsImages()
    {
        return $this->hasMany(\app\models\UsersVenuesRatingsImages::className(), ['user_venue_rating_id' => 'id'])->inverseOf('userVenueRating');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsersVenuesRatingsResponses()
    {
        return $this->hasMany(\app\models\UsersVenuesRatingsResponses::className(), ['user_venue_rating_id' => 'id'])->inverseOf('userVenueRating');
    }


    
    /**
     * @inheritdoc
     * @return \app\models\UsersVenuesRatingsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\UsersVenuesRatingsQuery(get_called_class());
    }


}
