<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

/**
 * This is the base-model class for table "venues_types".
 *
 * @property integer $id
 * @property string $venue_type_slug
 * @property string $venue_type_name
 * @property string $venue_type_description
 * @property integer $venue_type_active
 *
 * @property \app\models\Venues[] $venues
 * @property string $aliasModel
 */
abstract class VenuesTypes extends \yii\db\ActiveRecord {


    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'venues_types';
    }


    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['venue_type_active'], 'integer'],
            [['venue_type_slug'], 'string', 'max' => 20],
            [['venue_type_name'], 'string', 'max' => 100],
            [['venue_type_description'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'venue_type_slug' => 'Venue Type Slug',
            'venue_type_name' => 'Venue Type Name',
            'venue_type_description' => 'Venue Type Description',
            'venue_type_active' => 'Venue Type Active',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVenues() {
        return $this->hasMany(\app\models\Venues::className(), ['venue_type_id' => 'id']);
    }


    /**
     * @inheritdoc
     * @return \app\models\VenuesTypesQuery the active query used by this AR class.
     */
    public static function find() {
        return new \app\models\VenuesTypesQuery(get_called_class());
    }


}
