<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "venues_settings".
 *
 * @property integer $venue_id
 * @property string $venue_rating_category_mapping
 * @property integer $venue_rating_resolve_exp_days
 *
 * @property \app\models\Venues $venue
 * @property string $aliasModel
 */
abstract class VenuesSettings extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'venues_settings';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['venue_id'], 'required'],
            [['venue_id', 'venue_rating_resolve_exp_days'], 'integer'],
            [['venue_rating_category_mapping'], 'string'],
            [['venue_id'], 'unique'],
            [['venue_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Venues::className(), 'targetAttribute' => ['venue_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'venue_id' => 'Venue ID',
            'venue_rating_category_mapping' => 'Venue Rating Category Mapping',
            'venue_rating_resolve_exp_days' => 'Venue Rating Resolve Exp Days',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVenue()
    {
        return $this->hasOne(\app\models\Venues::className(), ['id' => 'venue_id'])->inverseOf('venuesSettings');
    }


    
    /**
     * @inheritdoc
     * @return \app\models\VenuesSettingsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\VenuesSettingsQuery(get_called_class());
    }


}
