<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "venues_coupons".
 *
 * @property integer $id
 * @property integer $venue_id
 * @property integer $venue_admin_id
 * @property string $coupon_name
 * @property string $coupon_code
 * @property integer $coupon_use_limit
 * @property integer $coupon_redeemed
 * @property string $coupon_redeem_date
 * @property string $coupon_expiration
 * @property string $coupon_created_date
 * @property string $coupon_modified_date
 * @property integer $coupon_active
 *
 * @property \app\models\UsersVenuesCoupons[] $usersVenuesCoupons
 * @property \app\models\Venues $venue
 * @property \app\models\VenuesAdmins $venueAdmin
 * @property string $aliasModel
 */
abstract class VenuesCoupons extends \yii\db\ActiveRecord
{


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'venues_coupons';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['venue_id', 'venue_admin_id', 'coupon_use_limit', 'coupon_redeemed', 'coupon_active'], 'integer'],
            [['coupon_redeem_date', 'coupon_expiration', 'coupon_created_date', 'coupon_modified_date'], 'safe'],
            [['coupon_name'], 'string', 'max' => 50],
            [['coupon_code'], 'string', 'max' => 20],
            [['venue_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Venues::className(), 'targetAttribute' => ['venue_id' => 'id']],
            [['venue_admin_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\VenuesAdmins::className(), 'targetAttribute' => ['venue_admin_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'venue_id' => 'Venue ID',
            'venue_admin_id' => 'Venue Admin ID',
            'coupon_name' => 'Coupon Name',
            'coupon_code' => 'Coupon Code',
            'coupon_use_limit' => 'Coupon Use Limit',
            'coupon_redeemed' => 'Coupon Redeemed',
            'coupon_redeem_date' => 'Coupon Redeem Date',
            'coupon_expiration' => 'Coupon Expiration',
            'coupon_created_date' => 'Coupon Created Date',
            'coupon_modified_date' => 'Coupon Modified Date',
            'coupon_active' => 'Coupon Active',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsersVenuesCoupons()
    {
        return $this->hasMany(\app\models\UsersVenuesCoupons::className(), ['venue_coupon_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVenue()
    {
        return $this->hasOne(\app\models\Venues::className(), ['id' => 'venue_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVenueAdmin()
    {
        return $this->hasOne(\app\models\VenuesAdmins::className(), ['id' => 'venue_admin_id']);
    }


    /**
     * @inheritdoc
     * @return \app\models\VenuesCouponsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\VenuesCouponsQuery(get_called_class());
    }


}
