<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "venues_images".
 *
 * @property integer $id
 * @property integer $venue_id
 * @property string $venue_image_url
 * @property string $venue_image_date_added
 *
 * @property \app\models\Venues $venue
 * @property string $aliasModel
 */
abstract class VenuesImages extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'venues_images';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['venue_id'], 'integer'],
            [['venue_image_url'], 'string'],
            [['venue_image_date_added'], 'safe'],
            [['venue_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Venues::className(), 'targetAttribute' => ['venue_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'venue_id' => 'Venue ID',
            'venue_image_url' => 'Venue Image Url',
            'venue_image_date_added' => 'Venue Image Date Added',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVenue()
    {
        return $this->hasOne(\app\models\Venues::className(), ['id' => 'venue_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\VenuesImagesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\VenuesImagesQuery(get_called_class());
    }


}
