<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "venues".
 *
 * @property integer $id
 * @property string $venue_name
 * @property string $venue_google_place_id
 * @property string $venue_date_added
 * @property string $venue_image_url
 * @property string $venue_address_1
 * @property string $venue_address_2
 * @property string $venue_city
 * @property string $venue_state
 * @property string $venue_phone
 * @property string $venue_email
 * @property string $venue_lat
 * @property string $venue_lon
 * @property integer $venue_active
 * @property string $aliasModel
 */
abstract class Venues extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'venues';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['venue_date_added'], 'safe'],
            [['venue_image_url'], 'string'],
            [['venue_lat', 'venue_lon'], 'number'],
            [['venue_active'], 'integer'],
            [['venue_name', 'venue_google_place_id', 'venue_address_1', 'venue_address_2', 'venue_email'], 'string', 'max' => 100],
            [['venue_city'], 'string', 'max' => 20],
            [['venue_state'], 'string', 'max' => 2],
            [['venue_phone'], 'string', 'max' => 16]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'venue_name' => 'Venue Name',
            'venue_google_place_id' => 'Venue Google Place ID',
            'venue_date_added' => 'Venue Date Added',
            'venue_image_url' => 'Venue Image Url',
            'venue_address_1' => 'Venue Address 1',
            'venue_address_2' => 'Venue Address 2',
            'venue_city' => 'Venue City',
            'venue_state' => 'Venue State',
            'venue_phone' => 'Venue Phone',
            'venue_email' => 'Venue Email',
            'venue_lat' => 'Venue Lat',
            'venue_lon' => 'Venue Lon',
            'venue_active' => 'Venue Active',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\VenuesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\VenuesQuery(get_called_class());
    }


}
